root_dir : "D:\\Data Science\\Gen AI\\Recomender_system\\artifacts\\"  # This is the root directory in my local system 
                                                                       # yo have to chaneg this location according your system

data_ingestion:
  path          : "D:\\Data Science\\Gen AI\\Recomender_system\\artifacts\\Data_Ingestion"
  resume_url    : "" #attach the source url of cloud from where all the resumes present
  projects_url  : "" # attah the url of cloud from where all projects can be downloaded
  resume_path   : "D:\\Data Science\\Gen AI\\Recomender_system\\artifacts\\Data_Ingestion\\resumes.zip"
  project_path  : "D:\\Data Science\\Gen AI\\Recomender_system\\artifacts\\Data_Ingestion\\projects.zip"
  unzip_path    : "D:\\Data Science\\Gen AI\\Recomender_system\\artifacts\\Data_Ingestion"

data_transformation:
  resumes_path   : "D:\\Data Science\\Gen AI\\Recomender_system\\artifacts\\Data_Ingestion\\Resumes"
  df_path        :  "D:\\Data Science\\Gen AI\\Recomender_system\\artifacts\\Data_Transformation"